export enum Routes {
  Prices = "prices",
  Payment = "payment",
  AboutUs = "about-us",
  Contacts = "contacts",
  CommonFridgeProblems = "common-fridge-problems",
  Reviews = "reviews",
  FAQ = "faq",

  //categories
  RepairsCategory = "repairs",

  //Subcategories
  OtherSubcategory = "other",
  CoolingSubcategory = "cooling",
  ElectricSubcategory = "electric",
  NofrostSystemSubcategory = "nofrost",
  MechanicalSubcategory = "mechanical",
  HullAndDoorsCubcategory = "hull-and-doors",

  //services - subcategory 1 (cooling)
  CompressorService = "compressor",
  EvaporatorService = "evaporator",
  CondensatorService = "condensator",
  CapillaryTubeService = "capillary-tube",
  CoolantService = "coolant",
  CoolantFoamService = "coolant-foam",
  CapillaryClogService = "capillary-clog",
  RefrigerantTopupService = "refrigerant-topup",
  FilterDryerService = "filter-dryer",
  SchraderValveService = "schrader-valve",
  PipelineService = "pipeline",
  EvaporatorSolderService = "evaporator-solder",
  ThermostatService = "thermostat",

  //services - subcategory 2 (electric)
  StartRelayService = "start-relay",
  SensorService = "sensor",
  TemperatureSensorService = "temperature-sensor",
  ControlModuleService = "control-module",
  ControlModuleCableService = "control-module-cable",
  ElectricalCircuitService = "electrical-circuit",
  ControlModuleRepairService = "control-module-repair",
  ControlBoardRepairService = "control-board-repair",
  ControlModuleSwapService = "control-module-swap",
  ElectricalCircuitRepairService = "electrical-circuit-repair",
  FirmwareUpdateService = "firmware-update",
  TimerService = "timer",
  DisplayCableService = "display-cable",
  PowerCableService = "power-cable",
  LedPowerSupplyService = "led-power-supply",
  FreezerTempSensorService = "freezer-temp-sensor",
  DoorSensorService = "door-sensor",
  HumiditySensorService = "humidity-sensor",

  //services - subcategory 3 (nofrost)
  HeatingElementService = "heating-element",
  DefrostHeaterService = "defrost-heater",
  EvaporatorHeaterService = "evaporator-heater",
  DefrostTimerService = "defrost-timer",
  NofrostFanService = "nofrost-fan",
  EvaporatorSensorService = "evaporator-sensor",
  DefrosterService = "defroster",
  FuseService = "fuse",
  NofrostDefrostService = "nofrost-defrost",

  //services - subcategory 4 (mechanical)
  FanService = "fan",
  FanInstallService = "fan-install",
  AirDamperService = "air-damper",
  DamperDriveService = "damper-drive",
  DrainagePumpService = "drainage-pump",

  //services - subcategory 5 (hull and doors)
  DoorRehingingService = "door-reehinging",
  DoorReplacementService = "door-replacement",
  DoorRepairService = "door-repair",
  DoorAdjustService = "door-adjust",
  DoorSealService = "door-seal",
  DoorHandleService = "door-handle",

  //services - subcategory 6 (other)
  DiagnosticsService = "diagnostics",
  DrainageService = "drainage",
  ExtraneousNoiseService = "extraneous-noise",
  LowTempBlockService = "low-temp-block",
  LightingService = "lighting-service",
  OdorRemovalService = "odor-removal",
  WaterIceDispenserService = "water-ice-dispenser",
  PreventiveMaintenanceService = "preventive-maintenance",
  ReprogrammingService = "reprogramming",
  ConsultationService = "consultation",
  InstallationService = "installation",
  ModernizationService = "modernization",
}
