export enum Routes {
  Prices = 'prices',
  Payment = 'payment',
  AboutUs = 'about-us',
  Contacts = 'contacts',
  CommonFridgeProblems = 'common-fridge-problems',
  Reviews = 'reviews',
  FAQ = 'faq',

  RepairsCategory = 'repairs',
  CoolingSubcategory = 'cooling',
  CompressorService = 'compressor',
  EvaporatorService = 'evaporator',
  CondensatorService = 'condensator',
  CapillaryTubeService = 'capillary-tube',
  CoolantService = 'coolant',
  ThermostatService = 'thermostat',
  ElectricSubcategory = 'electric',
  ControlModuleService = 'control-module',
  NofrostSystemSubcategory = 'nofrost',
  NofrostSystemService = 'nofrost-system',
  MechanicalSubcategory = 'mechanical',
  SealantService = 'sealant',
  VentilatorService = 'ventilator',
  HullAndDoorsCubcategory = 'hull-and-doors',
  OtherSubcategory = 'other',
  DiagnosticsService = 'diagnostics',
  DrainageService = 'drainage',
  ExtraneousNoiseService = 'extraneous-noise',
  LightingService = 'lighting-service',
}