import { Routes } from "@constants/routes";

export const serviceRouteStructure: Record<
  string,
  Record<string, Array<string>>
> = {
  [Routes.RepairsCategory]: {
    [Routes.CoolingSubcategory]: [
      Routes.CompressorService,
      Routes.EvaporatorService,
      Routes.CondensatorService,
      Routes.CapillaryTubeService,
      Routes.CoolantService,
      Routes.CoolantFoamService,
      Routes.CapillaryClogService,
      Routes.RefrigerantTopupService,
      Routes.FilterDryerService,
      Routes.SchraderValveService,
      Routes.PipelineService,
      Routes.EvaporatorSolderService,
      Routes.ThermostatService,
    ],
    [Routes.ElectricSubcategory]: [
      Routes.StartRelayService,
      Routes.SensorService,
      Routes.TemperatureSensorService,
      Routes.ControlModuleService,
      Routes.ControlModuleCableService,
      Routes.ElectricalCircuitService,
      Routes.ControlModuleRepairService,
      Routes.ControlBoardRepairService,
      Routes.ControlModuleSwapService,
      Routes.ElectricalCircuitRepairService,
      Routes.FirmwareUpdateService,
      Routes.TimerService,
      Routes.DisplayCableService,
      Routes.PowerCableService,
      Routes.LedPowerSupplyService,
      Routes.FreezerTempSensorService,
      Routes.DoorSensorService,
      Routes.HumiditySensorService,
    ],
    [Routes.NofrostSystemSubcategory]: [
      Routes.HeatingElementService,
      Routes.DefrostHeaterService,
      Routes.EvaporatorHeaterService,
      Routes.DefrostTimerService,
      Routes.NofrostFanService,
      Routes.EvaporatorSensorService,
      Routes.DefrosterService,
      Routes.FuseService,
      Routes.NofrostDefrostService,
    ],
    [Routes.MechanicalSubcategory]: [
      Routes.FanService,
      Routes.FanInstallService,
      Routes.AirDamperService,
      Routes.DamperDriveService,
      Routes.DrainagePumpService,
    ],
    [Routes.HullAndDoorsCubcategory]: [
      Routes.DoorRehingingService,
      Routes.DoorReplacementService,
      Routes.DoorRepairService,
      Routes.DoorAdjustService,
      Routes.DoorSealService,
      Routes.DoorHandleService,
    ],
    [Routes.OtherSubcategory]: [
      Routes.DiagnosticsService,
      Routes.DrainageService,
      Routes.ExtraneousNoiseService,
      Routes.LowTempBlockService,
      Routes.LightingService,
      Routes.OdorRemovalService,
      Routes.WaterIceDispenserService,
      Routes.PreventiveMaintenanceService,
      Routes.ReprogrammingService,
      Routes.ConsultationService,
      Routes.InstallationService,
      Routes.ModernizationService,
    ],
  },
};
