import { Routes } from "@constants/routes";

export const routeToLabelMap = new Map([
  [Routes.Prices, 'Цены'],
  [Routes.Payment, 'Оплата'],
  [Routes.AboutUs, 'О компании'],
  [Routes.Contacts, 'Контакты'],
  [Routes.CommonFridgeProblems, 'Частые проблемы с холодильником'],
  [Routes.Reviews, 'Отзывы'],
  [Routes.FAQ, 'Популярные вопросы'],
  [Routes.RepairsCategory, 'repairs'],
  [Routes.CoolingSubcategory, 'cooling'],
  [Routes.CompressorService, 'compressor'],
  [Routes.EvaporatorService, 'evaporator'],
  [Routes.CondensatorService, 'condensator'],
  [Routes.CapillaryTubeService, 'capillary-tube'],
  [Routes.CoolantService, 'coolant'],
  [Routes.ThermostatService, 'thermostat'],
  [Routes.ElectricSubcategory, 'electric'],
  [Routes.ControlModuleService, 'control-module'],
  [Routes.NofrostSystemSubcategory, 'nofrost'],
  [Routes.NofrostSystemService, 'nofrost-system'],
  [Routes.MechanicalSubcategory, 'mechanical'],
  [Routes.SealantService, 'sealant'],
  [Routes.VentilatorService, 'ventilator'],
  [Routes.HullAndDoorsCubcategory, 'hull-and-doors'],
  [Routes.OtherSubcategory, 'other'],
  [Routes.DiagnosticsService, 'diagnostics'],
  [Routes.DrainageService, 'drainage'],
  [Routes.ExtraneousNoiseService, 'extraneous-noise'],
  [Routes.LightingService, 'lighting-service'],
]);