import { Routes } from "@constants/routes";

export const routeToLabelMap = new Map([
  [Routes.Prices, 'Цены'],
  [Routes.Payment, 'Оплата'],
  [Routes.AboutUs, 'О компании'],
  [Routes.Contacts, 'Контакты'],
  [Routes.CommonFridgeProblems, 'Частые проблемы с холодильником'],
  [Routes.Reviews, 'Отзывы'],
  [Routes.FAQ, 'Популярные вопросы'],
  [Routes.RepairsCategory, 'Услуги по ремонту холодильников'],
  [Routes.CoolingSubcategory, 'Замена и ремонт компонентов системы охлаждения'],
  [Routes.CompressorService, 'Замена и ремонт компрессора'],
  [Routes.EvaporatorService, 'Замена испарителя'],
  [Routes.CondensatorService, 'Замена конденсатора'],
  [Routes.CapillaryTubeService, 'Замена капиллярной трубы'],
  [Routes.CoolantService, 'Заправка хладагентом (фреоном)'],
  [Routes.ThermostatService, 'Ремонт или замена термостата'],
  [Routes.ElectricSubcategory, 'Ремонт и замена электрических компонентов'],
  [Routes.ControlModuleService, 'Ремонт модуля управления'],
  [Routes.NofrostSystemSubcategory, 'Замена элементов системы No Frost'],
  [Routes.NofrostSystemService, 'Ремонт системы No Frost'],
  [Routes.MechanicalSubcategory, 'Замена и ремонт механических узлов'],
  [Routes.SealantService, 'Замена уплотнителя дверцы'],
  [Routes.VentilatorService, 'Замена вентилятора охлаждения'],
  [Routes.HullAndDoorsCubcategory, 'Ремонт дверей и корпуса'],
  [Routes.OtherSubcategory, 'Прочие услуги'],
  [Routes.DiagnosticsService, 'Диагностика неисправности'],
  [Routes.DrainageService, 'Прочистка дренажной системы'],
  [Routes.ExtraneousNoiseService, 'Устранение посторонних шумов'],
  [Routes.LightingService, 'Замена подсветки холодильника'],
]);